version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - t-ober
  - sensarmad
  - sebastian-peter
  - danielfeismann
  ignore:
  - dependency-name: org.jgrapht:jgrapht-core
    versions:
    - ">= 1.5.a, < 1.6"
